### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by CianFahy-Speire** [telabotanica/bp-moderate-group-creation#14] opened 2017-05-17 16:05 UTC
Hey When I activate the plugin I get a 500 error,I am running buddypress version 2.8.8

**Comment by kstefanini** [comment] 2017-05-18 08:58
Hey, sorry to hear that. Can you provide some details, like error stack trace or something ?

**Comment by CianFahy-Speire** [comment] 2017-05-18 10:23
Hey 

Here is the error that is coming up when in debug mode 

Fatal error: Class 'WP_List_Table' not found in /var/www/vhosts/79/830481/webspace/############## on line 21

**Comment by matcho** [comment] 2017-05-18 12:12
Duplicate of #12

**Closed as completed** 2017-05-18 12:15 UTC
